### ISSUE TITLE
Not able to convert files in a directory: illegal operation on a directory

### ISSUE THREAD

**Issue by jecfish** [cypress-io/cypress-chrome-recorder#11]
1. I have a **recordings** folder with a user flow json file in it.
2. Run `npx @cypress/chrome-recorder recordings`
3. Hit error `EISDIR: illegal operation on a directory, read` [NOT OK]

Expect all user flow JSON in the **recordings** folder are converted successfully.

Run `npx @cypress/chrome-recorder recordings/order-a-coffee.json` to convert a single JSON file is successful without error [OK].

<img width="937" alt="Screen Shot 2022-04-26 at 4 19 42 PM" src="https://user-images.githubusercontent.com/5917927/165255198-59755758-d587-4f42-89b3-140a5c424852.png">

**Comment by admah** [comment]
@jecfish you need to pass it `npx @cypress/chrome-recorder recordings/*.json`

I will update the examples to better demonstrate this.
