### ISSUE TITLE
Errors - Cypress does not currently handle migrating step type

### ISSUE THREAD

**Issue by jgwinner** [cypress-io/cypress-chrome-recorder#13]
I tried doing a fairly simple recording, or so I thought.

Went into our ERP and added a part. I ran the tool, and got this:

```
Cypress does not currently handle migrating step type: keyDown
Cypress does not currently handle migrating step type: keyUp
... 

```

It does seem to generate some files, with the text that I had entered, but the errors kind of threw me. I think this would nearly aways generate such errors if there is more to the recorded session than statically clicking on a page, so some mention of what this error means, and when or if it can be ignored would be good.

My guess is this can be ignored?

**Comment by jordanpowell88** [comment]
Hey John! We return that message after you run a migration for anything that we are not able to migrate with confidence to Cypress. You can ignore the message in some instances but other might require a bit of triaging to determine if any steps were missing after migrating. Does it run successfully in Cypress after converting?

**Comment by jgwinner** [comment]
Yes, it does run! The error message kind of threw me though.

I'd recommend changing to "Warning:" as then it's obvious that it's just a ... warning, otherwise I thought something was missing and was somewhat reticent toward trying the run.

Turned out, I was using ERPNext, and they don't give ID's to their screen elements, so this tool was the best way to get a reference to the screen objects!

        == John ==
