### ISSUE TITLE
Support double and right clicks

### ISSUE THREAD

**Issue by OrKoN** [cypress-io/cypress-chrome-recorder#20]
Hey there! 👋 

We have extended the Schema in @puppeteer/replay with some new attributes for the click step and a new step type called double click:

1) https://github.com/puppeteer/replay/blob/main/src/Schema.ts#L66
2) https://github.com/puppeteer/replay/blob/main/src/Schema.ts#L87

It'd be great to update the cypress recorder to support those. The feature will be shipping in Chromium 103.

**Comment by admah** [comment]
@OrKoN thanks for the heads-up! I've added PRs to address both of those additions.
