### ISSUE TITLE
Issue writing the output to cypress/integration

### ISSUE THREAD

**Issue by Puneet-humm** [cypress-io/cypress-chrome-recorder#27]
I have created a login.json file through chrome recorder and copied it to cypress\downloads.
 Now when I run "**npx  @cypress/chrome-recorder cypress\downloads\login.json**"
 OR "**npx @cypress/chrome-recorder cypress\downloads\login.json --print**" .

 I am getting the error **"There was an issue writing the output to cypress/integration. Please check that it exists and try again."**.
![image](https://user-images.githubusercontent.com/98075965/169160864-ffdcd794-85ad-45b2-b12e-4d22423fb178.png)

 Can anybody help me on this. Thanks

**Comment by Puneet-humm** [comment]
Hi Admah, I am using Cypress v 9.6.1 and chrome -recorder v 1.4.0

**Comment by admah** [comment]
@Puneet-humm does the `cypress/integration` folder exist? This won't write those folders. I've tested it with a similar file structure and can't reproduce what you're seeing. 

Also, I'm removing the `--print` flag in favor of `--dry`. Try to run it with that flag to see the output.

**Comment by Puneet-humm** [comment]
@admah , yes cypress/integration folder exist. 
Attached is the screenshot showing which commands are failing and which are passing. --dry is running fine.
<img width="566" alt="cypress" src="https://user-images.githubusercontent.com/98075965/170164042-3686e1bf-4944-46b7-b3b1-a54afe1aacbb.PNG">
.

**Comment by admah** [comment]
@Puneet-humm for the first command try:

`npx @cypress/chrome-recorder cypress/downloads/login.json --output=cypress/fixtures`

There shouldn't be a space after `--output=`. Also, you're using `\` for your paths instead of `/`.

**Comment by Puneet-humm** [comment]
What a silly thing I was doing, Its working now.

 Thanks a lot for your help :)
