### ISSUE TITLE
Support copy single step as Cypress script

### ISSUE THREAD

**Issue by jecfish** [cypress-io/cypress-chrome-recorder#42]
Chrome 109 launches a new "Copy a single step as script" feature. 

**How to test**
- In a recording, right click on a step, select copy as [your extension] script option. 

**Action required**
- Your extension needs to implement the [stringifyStep](https://developer.chrome.com/docs/extensions/reference/devtools_recorder/#examples) API for this feature to work.
- You can test this feature with the latest Chrome Canary

<img width="1131" alt="recorder-copy" src="https://user-images.githubusercontent.com/5917927/200954152-6c1f106b-8006-4cba-9c12-1967703e917a.png">

**Comment by jordanpowell88** [comment]
This is great! Thanks for the heads up

**Comment by OrKoN** [comment]
I have put up a PR here https://github.com/cypress-io/cypress-chrome-recorder/pull/41 (will look into signing the CLA later this week)
