### ISSUE TITLE
Cypress export don't work after new version (16/01)

### ISSUE THREAD

**Issue by Trevatron** [cypress-io/cypress-chrome-recorder#50]
Hello, I realized that I can no longer generate Cy code when I export the test through the recoder, the option is gone. Initially I tried to use it on other machines but they all give the same error.

![image](https://user-images.githubusercontent.com/55806079/213107026-1340b2d8-71ac-4c7c-924e-3f62acbd9272.png)

**Comment by tyogish** [comment]
This same issue is occurring at my side where i can't find the option to export script as .Cy file.

**Comment by shuai7** [comment]
i can't find the option Export as a Cypress Test Script

**Comment by miklosbalazsi-ws** [comment]
Same issue here
Cypress Chrome Recorder 1.1.0
Chrome Version 109.0.5414.75 (Official Build) (64-bit)

**Comment by Ru553llT** [comment]
i have the same issue. whats happened?

**Comment by w4dd325** [comment]
I'm also getting this same issue.
Cypress Chrome Recorder - Version 1.1.0
Chrome Version 109.0.5414.75 (Official Build) (64-bit)

**Comment by jordanpowell88** [comment]
Sorry about that everyone, we just submitted a patch release to the Chrome Store, that release should be published any day `1.1.1`

**Comment by riyadelberkawy** [comment]
@jordanpowell88 
### Isn't it a critical issue that we can't use the extension because of it?
The issue was opened on January 18th and the version in the store is still `1.1.0` until now.

**Comment by tyogish** [comment]
Hi, i can see the issue with the version 1.1.1, can you please look into.

**Comment by karen-law** [comment]
I am not sure what happened, but the export to cypress option is still missing. I am using the cypress chrome recorder updated on April 20.
![Screenshot 2023-11-01 at 4 23 27 PM](https://github.com/cypress-io/cypress-chrome-recorder/assets/137325587/48f18ce9-4899-473a-843f-91bb3871e790)

**Comment by karen-law** [comment]
It is there after I closed all chrome windows and restart chrome.

**Comment by polajenko** [comment]
I too can not see the cypress recorder after installing the extension, closing all chrome instances and rebooting windows 11 
![image](https://github.com/cypress-io/cypress-chrome-recorder/assets/4984308/21e5500e-0a04-4536-842c-49202ef19bb4)
