### ISSUE TITLE
Error during replay: `i.isIntersectingViewport is not a function`

### ISSUE THREAD

**Issue by richardkmichael** [cypress-io/cypress-chrome-recorder#52]
I just installed the latest Cypress Chrome Recorder, `Version 1.1.1`

In Chrome `Version 111.0.5563.64 (Official Build) (arm64)` on macOS `12.6.3`.

I created a recording successfully.  I have done this with the DevTools bottom-docked and also in a detached window.

When I replay the recording, it errors on the 3rd step with: `i.isIntersectingViewport is not a function`.

The first steps are:

```
Current page

> Set viewport
> Navigate

[new page title]

> Click  #==> error here: `i.isIntersectingViewport is not a function`
```

I tried deleting this step, but the same error occurs when it tries the "new" next step.

What additional information can I provide?

**Comment by mjhenkes** [comment]
@richardkmichael, It sounds like you may be having difficulties with the chrome recorder itself: https://developer.chrome.com/docs/devtools/recorder/

Are you seeing the error while exporting to a cypress test?

**Comment by richardkmichael** [comment]
Oh gosh, I probably am.  Sorry!  I thought the Cypress add-on is was added the `Recorder` tab 🤦   I have not seen or used this feature of Chrome before.

I didn't actually try using the test with Cypress, I had only tried Replay in the Chrome itself.

I'll investigate.
