### ISSUE TITLE
The plugin still looking for cypress/integration folder

### ISSUE THREAD

**Issue by mmonfared** [cypress-io/cypress-chrome-recorder#54]
Just simply tied to convert json to cy.js and got following error which means that the plugin still looking for integration folder which is for cypress v<10. (My cypress version is v12.11.0)

![image](https://github.com/cypress-io/cypress-chrome-recorder/assets/74588305/42289a74-72d8-4f5b-9dc0-1f73a14be4dd)

If I set output folder, of course it will resolved but the file name shows in console still contains `spec.js` not `cy.js` 

![image](https://github.com/cypress-io/cypress-chrome-recorder/assets/74588305/e4895585-88a5-4d0d-897c-0dbbc656da21)

**Comment by AtofStryker** [comment]
Hi @mmonfared . Thank you for opening an issue. I tried to create a reproduction repository [here](https://github.com/AtofStryker/cypress-chrome-recorder-issue-54) but I didn't run into the same issue you were experiencing. Is the recorder package at the latest version?

![Image](https://github.com/cypress-io/cypress-chrome-recorder/assets/3980464/75a840e8-5aec-47bf-9d4f-11539c3bcdeb)

**Comment by AtofStryker** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
