### ISSUE TITLE
@cypress/chrome-recorder doesn't exist on NPM

### ISSUE THREAD

**Issue by thedaviddias** [cypress-io/cypress-chrome-recorder#7]
If I'm not mistaken, the package is not available to be installed locally. Couldn't find it on NPM...

@admah @jordanpowell88

**Comment by admah** [comment]
@thedaviddias you are correct. This will be available on npm sometime next week.

**Comment by thedaviddias** [comment]
Amazing! Thank you for confirming! I'm looking forward to it and will give you feedback on that soon!

**Comment by admah** [comment]
@thedaviddias I’ll be sure to tag you once it’s officially out. Feedback and improvements are definitely welcome!

**Comment by admah** [comment]
@thedaviddias this just got published - https://github.com/cypress-io/cypress-chrome-recorder

**Comment by thedaviddias** [comment]
Amazing! Gonna try it and logged any issue I may find! Good job on that!
